definitions:
  app.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
  description: An example of gin
  license:
    name: MIT
    url: https://github.com/hallago/telepathy-server/blob/main/LICENSE
  termsOfService: https://github.com/hallago/telepathy-server
  title: Telepathy API
  version: 0.1.1
paths:
  /api/playerlist/{team_id}:
    get:
      parameters:
      - description: TEAM ID
        in: path
        name: team_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get player list by team id
  /api/teamlist:
    get:
      description: 구단정보 가져오기
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/app.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/app.Response'
      summary: Get team list
      tags:
      - 팀관련 API
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: X-api-key
    type: apiKey
swagger: "2.0"
